### ISSUE TITLE
Excited to find this tool - but currently not working well

### ISSUE THREAD

**Issue by danielstonehouse** [EmberLightVFX/XML-File-Copy#1]
Very excited to find this tool - As a short form colourists and former user of the Resolve Collect app (which has not been updated to be compatible with version 18) I really need a lightweight program to copy rushes from client drives to my storage.

After quite a tussle learning about pyenv, pip etc I have got it partially working - but It is unstable.

I've experimented with pyenv to try running it on the last version of python 2 - similar results to 3

Ive attached a screenshot and some error text is below

<img width="1752" alt="Screen Shot 2022-08-03 at 9 53 00 pm" src="https://user-images.githubusercontent.com/5334258/182601715-d5604bfa-df75-4199-a483-a60872938bda.png">

`
2022-08-03 21:50:44.990 python[35611:696764] -[NSNull length]: unrecognized selector sent to instance 0x7ff8516390b0
2022-08-03 21:50:44.990 python[35611:696764] Exception calling directoryDidChange: on delegate <QNSOpenSavePanelDelegate: 0x600003dd0460> exception=-[NSNull length]: unrecognized selector sent to instance 0x7ff8516390b0
2022-08-03 21:50:45.009 python[35611:696764] -[NSNull length]: unrecognized selector sent to instance 0x7ff8516390b0
2022-08-03 21:50:45.009 python[35611:696764] Exception calling directoryDidChange: on delegate <QNSOpenSavePanelDelegate: 0x600003dd0460> exception=-[NSNull length]: unrecognized selector sent to instance 0x7ff8516390b0
2022-08-03 21:51:29.135 python[35611:696764] -[NSNull length]: unrecognized selector sent to instance 0x7ff8516390b0
2022-08-03 21:51:29.135 python[35611:696764] Exception calling directoryDidChange: on delegate <QNSOpenSavePanelDelegate: 0x600003dd1ea0> exception=-[NSNull length]: unrecognized selector sent to instance 0x7ff8516390b0
2022-08-03 21:51:29.147 python[35611:696764] -[NSNull length]: unrecognized selector sent to instance 0x7ff8516390b0
2022-08-03 21:51:29.147 python[35611:696764] Exception calling directoryDidChange: on delegate <QNSOpenSavePanelDelegate: 0x600003dd1ea0> exception=-[NSNull length]: unrecognized selector sent to instance 0x7ff8516390b0
Traceback (most recent call last):
  File "xml_file_copy.py", line 172, in <lambda>
    lambda: self.getBasePath(self.ui.path_root))
  File "xml_file_copy.py", line 241, in getBasePath
    common_path = os.path.commonpath(files)
AttributeError: 'module' object has no attribute 'commonpath'
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
/Applications/XML-File-Copy-main/XML File Copy.command: line 4: 35611 Segmentation fault: 11  python "xml_file_copy.py"

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
`

**Comment by EmberLightVFX** [comment]
That's very weird... What version of Python are you running? I think you have to run at least Python 3.5 or later.
